name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move .well-known to public directory
        run: |
          mkdir -p public/.well-known
          mv .well-known/* public/.well-known/
          ls -R public/.well-known

      - name: Disable Jekyll (add .nojekyll file)
        run: |
          touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
